apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fish
  name: airflow-apiserver-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: airflow-apiserver-pv