apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    service: airflow-logs-pv
  name: airflow-logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/ubuntu/project/ffxiv-discord-fish-bot/airflow/pv/logs
  storageClassName: local-path