apiVersion: v1
kind: Service
metadata:
  namespace: fish
  labels:
    service: airflow-worker
  name: airflow-worker
spec:
  ports:
    - name: airflow-worker
      port: 8793
      targetPort: 8793 
  selector:
    service: airflow-worker
  type: ClusterIP