apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fish
  labels:
    service: postgres-db-volume
  name: postgres-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
