apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fish
  labels:
    service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
        - image: redis:latest
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 50
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 30
          name: airflow-redis
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
